name: Labot checks

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Start LanguageTool server
        run: |
          docker run -d --name languagetool \
            -p 8081:8081 \
            languagetoolorg/languagetool

      - name: Wait for LanguageTool to be ready
        run: |
          echo "Waiting for LanguageTool server to start..."
          for i in {1..60}; do
            if curl -s http://localhost:8081/v2/check -d '{}' -H "Content-Type: application/json" | grep -q '"matches"'; then
              echo "LanguageTool is ready."
              exit 0
            fi
            echo "Waiting... ($i)"
            sleep 2
          done
          echo "LanguageTool failed to start in time."
          docker logs languagetool
          exit 1


      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/digital-work-lab/labot.git
          pip install colrev

      - name: Set Git user name and email
        run: |
          git config --global user.email "digital-work-labot@users.noreply.github.com"
          git config --global user.name "digital-work-labot"
          git config --global url.https://github.com/.insteadOf git://github.com/

      - name: Workaround for detached HEAD (for PRs)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin '+refs/heads/*:refs/remotes/origin/*'
          git checkout ${GITHUB_HEAD_REF#refs/heads/} || \
          git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull

      - name: Run labot.repository.main()
        run: |
          python -m labot.repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}

      - name: Stop LanguageTool container
        if: always()
        run: docker rm -f languagetool || true
