name: Spellcheck and Report

on:
  push:
    paths:
      - '**.md'
      - '**.txt'
  pull_request:
    paths:
      - '**.md'
      - '**.txt'
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cspell
        run: npm install -g cspell

      - name: Run cspell and save to file
        run: |
          mkdir -p tmp
          find . -name '*.md' -o -name '*.txt' | xargs cspell --config .cspell.json > tmp/spellcheck-report.md || true

      - name: Check if spelling errors were found
        id: check_errors
        run: |
          if [ -s tmp/spellcheck-report.md ]; then
            echo "has_errors=true" >> $GITHUB_OUTPUT
          else
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Issue From File
        if: steps.check_errors.outputs.has_errors == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Spellcheck Report: Spelling Issues Found"
          content-filepath: tmp/spellcheck-report.md
          labels: |
            spelling
            automated issue
          issue-number: "413"
          assignees: "geritwagner"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue if No Errors
        if: steps.check_errors.outputs.has_errors == 'false'
        uses: peter-evans/close-issue@v3
        with:
          issue-number: 413
          comment: |
            ✅ No spelling errors were found in the latest check.
            This issue is being automatically closed.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
