name: Spellcheck and Report

on:
  push:
    paths:
      - '**.md'
      - '**.txt'
  pull_request:
    paths:
      - '**.md'
      - '**.txt'
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run spellcheck
        id: spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        continue-on-error: true

      - name: Copy output to file for issue
        run: |
          mkdir -p tmp
          if [ -f .spellcheck-output.txt ]; then
            cp .spellcheck-output.txt tmp/spellcheck-report.md
          else
            echo "⚠️ No .spellcheck-output.txt generated. Spellcheck may not have found any issues or misconfigured output." > tmp/spellcheck-report.md
          fi

      - name: Check if spellcheck report has content
        id: check_errors
        run: |
          if [ -s tmp/spellcheck-report.md ]; then
            echo "has_errors=true" >> $GITHUB_OUTPUT
          else
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Issue From File
        if: steps.check_errors.outputs.has_errors == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Spellcheck Report: Spelling Issues Found"
          content-filepath: tmp/spellcheck-report.md
          labels: |
            spelling
            automated issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
