name: Update repository overview
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Change to Repo Directory
        run: cd ${{ github.workspace }}

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.LABOT_PAT_TOKEN }}
        run: |
          python src/update_repositories.py
      
      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.LABOT_PAT_TOKEN }}
        run: |
          git config --global user.email "digital-work-labot@users.noreply.github.com"
          git config --global user.name "digital-work-labot"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Update repository overview"
            git push
          else
            echo "No changes to commit"
          fi
